import type { CatalogRangeSeed } from "@/lib/catalog/range-product";

const FAMILY = "robinets-soupape-pointeau";
const SUB = "robinets-pied-de-colonne-perfection-a-flotteur";

function frEn(fr: string, en: string) {
  return { fr, en };
}

/** Pied de colonne, perfection, robinets à flotteur et flotteurs seuls. */
export const columnFootFloatValveRanges: CatalogRangeSeed[] = [
  {
    reference: "430",
    slug: "serie-430-robinet-soupape-perfection-male-bsp",
    name: frEn("Robinet à soupape perfection — mâle BSP", "Perfection pattern globe valve — male BSP"),
    description: frEn("Pied de colonne, réseaux eau sanitaire.", "Column foot, domestic water networks."),
    dn: null,
    pn: null,
    material: frEn("Laiton", "Brass"),
    familySlug: FAMILY,
    subfamilySlug: SUB,
    listingKind: "range",
    connectionType: "threaded",
    standards: ["en10204"],
    sectorTags: ["water"],
    technicalSpecs: { connection: "bsp", documentCount: 4 },
  },
  {
    reference: "490",
    slug: "serie-490-robinet-pointeau-flotteur-pe-acs",
    name: frEn(
      "Robinet à pointeau laiton — flotteur polyéthylène ACS",
      "Brass needle valve — polyethylene float ACS",
    ),
    description: frEn("Régulation niveau cuve, eau potable ACS.", "Tank level control, ACS potable water."),
    dn: null,
    pn: null,
    material: frEn("Laiton", "Brass"),
    familySlug: FAMILY,
    subfamilySlug: SUB,
    listingKind: "range",
    connectionType: "threaded",
    standards: ["en10204"],
    sectorTags: ["water"],
    technicalSpecs: { documentCount: 4 },
  },
  {
    reference: "491",
    slug: "serie-491-robinet-pointeau-flotteur-cuivre-acs",
    name: frEn(
      "Robinet à pointeau laiton — flotteur cuivre ACS",
      "Brass needle valve — copper float ACS",
    ),
    description: frEn("Flotteur cuivre, même gamme ACS.", "Copper float, same ACS range."),
    dn: null,
    pn: null,
    material: frEn("Laiton", "Brass"),
    familySlug: FAMILY,
    subfamilySlug: SUB,
    listingKind: "range",
    connectionType: "threaded",
    standards: ["en10204"],
    sectorTags: ["water"],
    technicalSpecs: { documentCount: 4 },
  },
  {
    reference: "492",
    slug: "serie-492-robinet-flotteur-athena-fonte",
    name: frEn("Robinet flotteur Athéna fonte", "Athéna cast iron float valve"),
    description: frEn("Flotteur intégré, réservoirs et surpresse.", "Integrated float, tanks and boosting."),
    dn: null,
    pn: null,
    material: frEn("Fonte", "Cast iron"),
    familySlug: FAMILY,
    subfamilySlug: SUB,
    listingKind: "range",
    connectionType: "threaded",
    standards: ["en10204"],
    sectorTags: ["water"],
    technicalSpecs: { bodyProcess: "cast", documentCount: 4 },
  },
  {
    reference: "494",
    slug: "serie-494-robinet-pointeau-flotteur-inox",
    name: frEn(
      "Robinet à pointeau inox — flotteur inox",
      "Stainless needle valve — stainless float",
    ),
    description: frEn("Inox intégral, milieux agressifs.", "All-stainless, aggressive media."),
    dn: null,
    pn: null,
    material: frEn("Inox", "Stainless steel"),
    familySlug: FAMILY,
    subfamilySlug: SUB,
    listingKind: "range",
    connectionType: "threaded",
    standards: ["en10204"],
    sectorTags: ["water", "agro"],
    technicalSpecs: { documentCount: 4 },
  },
  {
    reference: "980620",
    slug: "serie-980620-flotteur-seul-pe",
    name: frEn(
      "Flotteur seul polyéthylène — robinet flotteur",
      "Spare polyethylene float — float valve",
    ),
    description: frEn("Pièce de rechange gamme PE.", "PE range spare part."),
    dn: null,
    pn: null,
    material: frEn("Polyéthylène", "Polyethylene"),
    familySlug: FAMILY,
    subfamilySlug: SUB,
    listingKind: "range",
    sectorTags: ["water"],
    technicalSpecs: { documentCount: 2 },
  },
  {
    reference: "980630",
    slug: "serie-980630-flotteur-seul-cuivre",
    name: frEn("Flotteur seul cuivre — robinet flotteur", "Spare copper float — float valve"),
    description: frEn("Rechange flotteur cuivre.", "Copper float replacement."),
    dn: null,
    pn: null,
    material: frEn("Cuivre", "Copper"),
    familySlug: FAMILY,
    subfamilySlug: SUB,
    listingKind: "range",
    sectorTags: ["water"],
    technicalSpecs: { documentCount: 2 },
  },
  {
    reference: "980632",
    slug: "serie-980632-flotteur-seul-inox",
    name: frEn("Flotteur seul inox — robinet flotteur inox", "Spare stainless float — SS float valve"),
    description: frEn("Rechange flotteur inox.", "Stainless float replacement."),
    dn: null,
    pn: null,
    material: frEn("Inox", "Stainless steel"),
    familySlug: FAMILY,
    subfamilySlug: SUB,
    listingKind: "range",
    sectorTags: ["water"],
    technicalSpecs: { documentCount: 2 },
  },
];
