import type { CatalogRangeSeed } from "@/lib/catalog/range-product";

const FAMILY = "robinetterie-petrole-forgee-moulee";
const SUB = "clapets-petrole-forge-moule";

function frEn(fr: string, en: string) {
  return { fr, en };
}

function slug(ref: string, suffix: string) {
  return `serie-${ref}-clapet-petrole-${suffix}`;
}

/** Clapets pétrole forgé / moulé — gammes par série. */
export const petroleumCheckValveRanges: CatalogRangeSeed[] = [
  {
    reference: "312",
    slug: slug("312", "piston-ressort-sw"),
    name: frEn(
      "Clapet anti-retour à piston avec ressort — SW",
      "Piston check valve with spring — socket weld",
    ),
    description: frEn(
      "Acier, ressort intégré, soudure socket — lignes hydrocarbures.",
      "Steel, spring-loaded, socket weld — hydrocarbon lines.",
    ),
    dn: null,
    pn: "Class 800",
    material: frEn("Acier", "Steel"),
    familySlug: FAMILY,
    subfamilySlug: SUB,
    listingKind: "range",
    connectionType: "sw",
    standards: ["en10204"],
    sectorTags: ["energy"],
    certified31: true,
    technicalSpecs: { pressureClass: "Class 800", connection: "sw", documentCount: 4 },
  },
  {
    reference: "313",
    slug: slug("313", "piston-ressort-npt"),
    name: frEn("Clapet anti-retour à piston avec ressort — NPT", "Piston check valve with spring — NPT"),
    description: frEn("Raccordement NPT, même principe piston/ressort.", "NPT ends, same piston/spring design."),
    dn: null,
    pn: "Class 800",
    material: frEn("Acier", "Steel"),
    familySlug: FAMILY,
    subfamilySlug: SUB,
    listingKind: "range",
    connectionType: "threaded",
    standards: ["en10204"],
    sectorTags: ["energy"],
    certified31: true,
    technicalSpecs: { pressureClass: "Class 800", connection: "npt", documentCount: 4 },
  },
  {
    reference: "314",
    slug: slug("314", "piston-ressort-bsp"),
    name: frEn("Clapet anti-retour à piston avec ressort — BSP", "Piston check valve with spring — BSP"),
    description: frEn("BSP taraudé, anti-retour compact en ligne.", "Threaded BSP, compact in-line check."),
    dn: null,
    pn: "Class 800",
    material: frEn("Acier", "Steel"),
    familySlug: FAMILY,
    subfamilySlug: SUB,
    listingKind: "range",
    connectionType: "threaded",
    standards: ["en10204"],
    sectorTags: ["energy"],
    technicalSpecs: { pressureClass: "Class 800", connection: "bsp", documentCount: 4 },
  },
  {
    reference: "318",
    slug: slug("318", "forge-bille-ressort-sw"),
    name: frEn("Clapet anti-retour acier forgé à bille — SW", "Forged steel ball check valve — SW"),
    description: frEn(
      "Corps forgé, clapet à bille et ressort, haute étanchéité.",
      "Forged body, ball and spring check, high sealing integrity.",
    ),
    dn: null,
    pn: "Class 800",
    material: frEn("Acier forgé A105N", "Forged steel A105N"),
    familySlug: FAMILY,
    subfamilySlug: SUB,
    listingKind: "range",
    connectionType: "sw",
    standards: ["en10204"],
    sectorTags: ["energy"],
    certified31: true,
    technicalSpecs: { pressureClass: "Class 800", connection: "sw", bodyProcess: "forged", documentCount: 4 },
  },
  {
    reference: "319",
    slug: slug("319", "forge-bille-ressort-npt"),
    name: frEn("Clapet anti-retour acier forgé à bille — NPT", "Forged steel ball check valve — NPT"),
    description: frEn("Gamme bille forgée, NPT F/F.", "Forged ball check range, NPT F/F."),
    dn: null,
    pn: "Class 800",
    material: frEn("Acier forgé A105N", "Forged steel A105N"),
    familySlug: FAMILY,
    subfamilySlug: SUB,
    listingKind: "range",
    connectionType: "threaded",
    standards: ["en10204"],
    sectorTags: ["energy"],
    certified31: true,
    technicalSpecs: { pressureClass: "Class 800", connection: "npt", bodyProcess: "forged", documentCount: 4 },
  },
  {
    reference: "358",
    slug: slug("358", "inox-forge-bille-sw"),
    name: frEn("Clapet anti-retour inox forgé à bille — SW", "Forged stainless ball check valve — SW"),
    description: frEn("Inox forgé, fluides corrosifs et process pétrochimie.", "Forged stainless, corrosive and petrochemical service."),
    dn: null,
    pn: "Class 800",
    material: frEn("Inox forgé F316", "Forged F316 stainless"),
    familySlug: FAMILY,
    subfamilySlug: SUB,
    listingKind: "range",
    connectionType: "sw",
    standards: ["en10204"],
    sectorTags: ["energy", "agro"],
    certified31: true,
    technicalSpecs: { pressureClass: "Class 800", connection: "sw", bodyProcess: "forged", documentCount: 4 },
  },
  {
    reference: "359",
    slug: slug("359", "inox-forge-bille-npt"),
    name: frEn("Clapet anti-retour inox forgé à bille — NPT", "Forged stainless ball check valve — NPT"),
    description: frEn("F316, NPT, anti-retour haute pression.", "F316, NPT, high-pressure check."),
    dn: null,
    pn: "Class 800",
    material: frEn("Inox forgé F316", "Forged F316 stainless"),
    familySlug: FAMILY,
    subfamilySlug: SUB,
    listingKind: "range",
    connectionType: "threaded",
    standards: ["en10204"],
    sectorTags: ["energy"],
    certified31: true,
    technicalSpecs: { pressureClass: "Class 800", connection: "npt", bodyProcess: "forged", documentCount: 4 },
  },
  {
    reference: "373",
    slug: slug("373", "battant-brides-class150"),
    name: frEn("Clapet simple battant acier — brides Class 150", "Swing check valve steel — Class 150 RF"),
    description: frEn(
      "Clapet à battant, corps acier, brides RF — réseaux pétrole.",
      "Swing check, steel body, RF flanges — oil networks.",
    ),
    dn: null,
    pn: "PN20",
    material: frEn("Acier", "Steel"),
    familySlug: FAMILY,
    subfamilySlug: SUB,
    listingKind: "range",
    connectionType: "flanged-rf",
    standards: ["en10204"],
    sectorTags: ["energy"],
    technicalSpecs: { pressureClass: "Class 150", connection: "flanged-rf", bodyProcess: "cast", documentCount: 4 },
  },
  {
    reference: "374",
    slug: slug("374", "battant-brides-class300"),
    name: frEn("Clapet simple battant acier — brides Class 300", "Swing check valve steel — Class 300 RF"),
    description: frEn("Class 300 PN50, anti-retour sur lignes sous pression.", "Class 300 PN50, check on pressurized lines."),
    dn: null,
    pn: "PN50",
    material: frEn("Acier", "Steel"),
    familySlug: FAMILY,
    subfamilySlug: SUB,
    listingKind: "range",
    connectionType: "flanged-rf",
    standards: ["en10204"],
    sectorTags: ["energy"],
    technicalSpecs: { pressureClass: "Class 300", connection: "flanged-rf", bodyProcess: "cast", documentCount: 4 },
  },
];
