import type { CatalogRangeSeed } from "@/lib/catalog/range-product";

const FAMILY = "robinets-tournant-spherique-acier-inox";
const SUB = "robinets-tournant-spherique-2-pieces-split-body";

function frEn(fr: string, en: string) { return { fr, en }; }

function base(
  partial: Omit<CatalogRangeSeed, "familySlug" | "subfamilySlug" | "listingKind">,
): CatalogRangeSeed {
  return { ...partial, listingKind: "range", familySlug: FAMILY, subfamilySlug: SUB };
}

/** Robinets 2 pièces split body à brides — JC, FM2, Adler, Performance, etc. */
export const splitBodyBallValveRanges: CatalogRangeSeed[] = [
  base({
    reference: "316-340iicg",
    slug: "serie-316-340iicg-robinet-a-tournant-spherique-2-pieces-f1-inox-jc-graphite-pn16-40",
    name: frEn("316-340IICG - Robinet à tournant sphérique 2 pièces F1 inox JC graphite PN16/40", "316 — 340IICG - Ball valve two-piece F1 stainless JC graphite PN16/40"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN16-40", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "316-340qiit",
    slug: "serie-316-340qiit-robinet-a-tournant-spherique-2-pieces-f1-inox-jc-tfm1600-pn16-40",
    name: frEn("316/340QIIT - Robinet à tournant sphérique 2 pièces F1 inox JC TFM1600 PN16/40", "316/340QIIT - Ball valve two-piece F1 stainless JC TFM1600 PN16/40"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN16-40", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "316aicg",
    slug: "serie-316aicg-robinet-a-tournant-spherique-2-pieces-f1-acier-jc-graphite-pn16-40",
    name: frEn("316AICG - Robinet à tournant sphérique 2 pièces F1 acier JC graphite PN16/40", "316AICG - Ball valve two-piece F1 steel JC graphite PN16/40"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN16-40", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "316ait-340ait",
    slug: "serie-316ait-340ait-robinet-a-tournant-spherique-2-pieces-f1-acier-jc-ptfe-pn16-40",
    name: frEn("316AIT/340AIT - Robinet à tournant sphérique 2 pièces F1 acier JC PTFE PN16/40", "316AIT/340AIT - Ball valve two-piece F1 steel JC PTFE PN16/40"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN16-40", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "316iit-340iit",
    slug: "serie-316iit-340iit-robinet-a-tournant-spherique-2-pieces-f1-inox-jc-ptfe-pn16-40",
    name: frEn("316IIT/340IIT - Robinet à tournant sphérique 2 pièces F1 inox JC PTFE PN16/40", "316IIT/340IIT - Ball valve two-piece F1 stainless JC PTFE PN16/40"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN16-40", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "340aigf",
    slug: "serie-340aigf-robinet-a-tournant-spherique-2-pieces-f1-acier-jc-verre-pn16-40",
    name: frEn("340AIGF - Robinet à tournant sphérique 2 pièces F1 acier JC verre PN16/40", "340AIGF - Ball valve two-piece F1 steel JC verre PN16/40"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN16-40", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "340ais-316ais",
    slug: "serie-340ais-316ais-robinet-tournant-spherique-2-pieces-f1-acier-jc-stansit-pn16-40",
    name: frEn("340AIS-316AIS - Robinet tournant sphérique 2 pièces F1 acier JC stansit PN16/40", "340AIS-316AIS - Ball valve two-piece F1 steel JC stansit PN16/40"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN16-40", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "340iigf-316iigf",
    slug: "serie-340iigf-316iigf-robinet-a-tournant-spherique-2-pieces-f1-inox-jc-verre-pn16-40",
    name: frEn("340IIGF-316IIGF - Robinet à tournant sphérique 2 pièces F1 inox JC verre PN16/40", "340IIGF-316IIGF - Ball valve two-piece F1 stainless JC verre PN16/40"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN16-40", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "340iis-316iis",
    slug: "serie-340iis-316iis-robinet-tournant-spherique-2-pieces-f1-inox-jc-stansit-pn16-40",
    name: frEn("340IIS-316IIS - Robinet tournant sphérique 2 pièces F1 inox JC stansit PN16/40", "340IIS-316IIS - Ball valve two-piece F1 stainless JC stansit PN16/40"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN16-40", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "515aigf",
    slug: "serie-515aigf-robinet-a-tournant-spherique-2-pieces-acier-jc-verre-class150-pn20",
    name: frEn("515AIGF - Robinet à tournant sphérique 2 pièces acier JC verre class150 PN20", "515AIGF - Ball valve two-piece steel JC verre class150 PN20"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 150", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "515ait",
    slug: "serie-515ait-robinet-a-tournant-spherique-2-pieces-acier-jc-ptfe-class150-pn20",
    name: frEn("515AIT - Robinet à tournant sphérique 2 pièces acier JC PTFE class150 PN20", "515AIT - Ball valve two-piece steel JC PTFE class150 PN20"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 150", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "515iigf",
    slug: "serie-515iigf-robinet-a-tournant-spherique-2-pieces-inox-jc-ptfe-verre-class150-pn20",
    name: frEn("515IIGF - Robinet à tournant sphérique 2 pièces inox JC PTFE verre class150 PN20", "515IIGF - Ball valve two-piece stainless JC PTFE verre class150 PN20"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 150", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "515iit",
    slug: "serie-515iit-robinet-a-tournant-spherique-2-pieces-inox-jc-ptfe-class150-pn20",
    name: frEn("515IIT - Robinet à tournant sphérique 2 pièces inox JC PTFE class150 PN20", "515IIT - Ball valve two-piece stainless JC PTFE class150 PN20"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 150", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "515qiit",
    slug: "serie-515qiit-robinet-a-tournant-spherique-2-pieces-inox-class-150-pn20-jc-tfm1600",
    name: frEn("515QIIT - Robinet à tournant sphérique 2 pièces inox Class 150 PN20 JC TFM1600", "515QIIT - Ball valve two-piece stainless Class 150 PN20 JC TFM1600"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN20", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "516-540qiit",
    slug: "serie-516-540qiit-robinet-a-tournant-spherique-2-pieces-f4-inox-jc-tfm1600-pn16-40",
    name: frEn("516/540QIIT - Robinet à tournant sphérique 2 pièces F4 inox JC TFM1600 PN16/40", "516/540QIIT - Ball valve two-piece F4 stainless JC TFM1600 PN16/40"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN16-40", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "516aicg-540aicg",
    slug: "serie-516aicg-540aicg-robinet-a-tournant-spherique-2-pcs-f4-acier-jc-graphite-pn40",
    name: frEn("516AICG/540AICG - Robinet à tournant sphérique 2 pcs F4 acier JC graphite PN40", "516AICG/540AICG - Ball valve 2 pcs F4 steel JC graphite PN40"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN40", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "516aigf-540aigf",
    slug: "serie-516aigf-540aigf-robinet-a-tournant-spherique-2-pieces-f4-acier-jc-ptfeplusverre",
    name: frEn("516AIGF/540AIGF - Robinet à tournant sphérique 2 pièces F4 acier JC PTFE+verre", "516AIGF/540AIGF - Ball valve two-piece F4 steel JC PTFE+verre"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN16-40", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "516ais-540ais",
    slug: "serie-516ais-540ais-robinet-a-tournant-spherique-2-pieces-f4-acier-jc-stansit-pn40",
    name: frEn("516AIS/540AIS - Robinet à tournant sphérique 2 pièces F4 acier JC stansit PN40", "516AIS/540AIS - Ball valve two-piece F4 steel JC stansit PN40"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN40", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "516ait-540ait",
    slug: "serie-516ait-540ait-robinet-a-tournant-spherique-2-pieces-f4-acier-jc-ptfe-pn40",
    name: frEn("516AIT/540AIT - Robinet à tournant sphérique 2 pièces F4 acier JC PTFE PN40", "516AIT/540AIT - Ball valve two-piece F4 steel JC PTFE PN40"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN40", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "516iicg",
    slug: "serie-516iicg-robinet-a-tournant-spherique-2-pieces-f4-inox-jc-graphite",
    name: frEn("516IICG - Robinet à tournant sphérique 2 pièces F4 inox JC graphite", "516IICG - Ball valve two-piece F4 stainless JC graphite"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN16-40", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "516iigf-540iigf",
    slug: "serie-516iigf-540iigf-robinet-a-tournant-spherique-2-pcs-f4-inox-jc-ptfeplusverre-pn40",
    name: frEn("516IIGF/540IIGF - Robinet à tournant sphérique 2 pcs F4 inox JC PTFE+verre PN40", "516IIGF/540IIGF - Ball valve 2 pcs F4 stainless JC PTFE+verre PN40"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN40", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "516iis-540iis",
    slug: "serie-516iis-540iis-robinet-a-tournant-spherique-2-pieces-f4-inox-jc-stansit-pn40",
    name: frEn("516IIS/540IIS - Robinet à tournant sphérique 2 pièces F4 inox JC stansit PN40", "516IIS/540IIS - Ball valve two-piece F4 stainless JC stansit PN40"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN40", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "530aigf",
    slug: "serie-530aigf-robinet-a-tournant-spherique-2-pieces-acier-jc-ptfe-verre-class300",
    name: frEn("530AIGF - Robinet à tournant sphérique 2 pièces acier JC PTFE verre class300", "530AIGF - Ball valve two-piece steel JC PTFE verre class300"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 300", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "530ait",
    slug: "serie-530ait-robinet-a-tournant-spherique-2-pieces-acier-jc-ptfe-class300-pn50",
    name: frEn("530AIT - Robinet à tournant sphérique 2 pièces acier JC PTFE class300 PN50", "530AIT - Ball valve two-piece steel JC PTFE class300 PN50"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 300", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "530iigf",
    slug: "serie-530iigf-robinet-a-tournant-spherique-2-pieces-inox-jc-ptfe-verre-class300-pn50",
    name: frEn("530IIGF -Robinet à tournant sphérique 2 pièces inox JC PTFE verre class300 PN50", "530IIGF -Ball valve two-piece stainless JC PTFE verre class300 PN50"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 300", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "530iit",
    slug: "serie-530iit-robinet-a-tournant-spherique-2-pieces-inox-jc-ptfe-class300-pn50",
    name: frEn("530IIT - Robinet à tournant sphérique 2 pièces inox JC PTFE class300 PN50", "530IIT - Ball valve two-piece stainless JC PTFE class300 PN50"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 300", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "530qiit",
    slug: "serie-530qiit-robinet-a-tournant-spherique-2-pieces-inox-class-300-pn50-jc-tfm1600",
    name: frEn("530QIIT - Robinet à tournant sphérique 2 pièces inox Class 300 PN50 JC TFM1600", "530QIIT - Ball valve two-piece stainless Class 300 PN50 JC TFM1600"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN50", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "540iit",
    slug: "serie-540iit-robinet-a-tournant-spherique-2-pieces-f4-inox-jc-ptfe-pn40",
    name: frEn("540IIT - Robinet à tournant sphérique 2 pièces F4 inox JC PTFE PN40", "540IIT - Ball valve two-piece F4 stainless JC PTFE PN40"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN40", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "715ait",
    slug: "serie-715ait-robinet-a-tournant-spherique-end-entry-acier-monobloc-jc-class150",
    name: frEn("715AIT - Robinet à tournant sphérique end entry acier monobloc JC class150", "715AIT - Ball valve End entry steel monobloc JC class150"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 150", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "715iit",
    slug: "serie-715iit-robinet-a-tournant-spherique-end-entry-inox-monobloc-jc-class150",
    name: frEn("715IIT - Robinet à tournant sphérique end entry inox monobloc JC class150", "715IIT - Ball valve End entry stainless monobloc JC class150"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 150", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "730ait",
    slug: "serie-730ait-robinet-a-tournant-spherique-end-entry-acier-monobloc-jc-class300",
    name: frEn("730AIT - Robinet à tournant sphérique end entry acier monobloc JC class300", "730AIT - Ball valve End entry steel monobloc JC class300"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 300", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "730iit",
    slug: "serie-730iit-robinet-a-tournant-spherique-end-entry-inox-monobloc-jc-class300",
    name: frEn("730IIT - Robinet à tournant sphérique end entry inox monobloc JC class300", "730IIT - Ball valve End entry stainless monobloc JC class300"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 300", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "750",
    slug: "serie-750-robinet-a-tournant-spherique-2-pieces-a-brides-acier-fm2",
    name: frEn("750 - Robinet à tournant sphérique 2 pièces à brides acier FM2", "750 — Ball valve two-piece flanged steel FM2"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN16-40", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "751",
    slug: "serie-751-robinet-a-tournant-spherique-2-pieces-a-brides-inox-fm2",
    name: frEn("751 - Robinet à tournant sphérique 2 pièces à brides inox FM2", "751 — Ball valve two-piece flanged stainless FM2"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN16-40", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "752",
    slug: "serie-752-robinet-a-tournant-spherique-acier-2-pieces-a-brides-excellence-pn16-40",
    name: frEn("752 - Robinet à tournant sphérique acier 2 pièces à brides Excellence PN16/40", "752 — Ball valve steel two-piece flanged Excellence PN16/40"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN16-40", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "753",
    slug: "serie-753-robinet-a-tournant-spherique-2-pieces-a-brides-inox-excellence-pn16-pn40",
    name: frEn("753 - Robinet à tournant sphérique 2 pièces à brides inox Excellence PN16/PN40", "753 — Ball valve two-piece flanged stainless Excellence PN16/PN40"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN16-40", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "754",
    slug: "serie-754-robinet-a-tournant-spherique-2-pieces-a-brides-acier-adler",
    name: frEn("754 - Robinet à tournant sphérique 2 pièces à brides acier ADLER", "754 — Ball valve two-piece flanged steel ADLER"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN16-40", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "755",
    slug: "serie-755-robinet-a-tournant-spherique-2-pieces-a-brides-inox-adler-pn16-25",
    name: frEn("755 - Robinet à tournant sphérique 2 pièces à brides inox ADLER PN16/25", "755 — Ball valve two-piece flanged stainless ADLER PN16/25"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN16", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "756",
    slug: "serie-756-robinet-a-tournant-spherique-2-pieces-a-brides-acier-class150-pn20",
    name: frEn("756 - Robinet à tournant sphérique 2 pièces à brides acier class150 PN20", "756 — Ball valve two-piece flanged steel class150 PN20"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 150", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "757",
    slug: "serie-757-robinet-a-tournant-spherique-2-pieces-a-brides-inox-class150",
    name: frEn("757 - Robinet à tournant sphérique 2 pièces à brides inox class150", "757 — Ball valve two-piece flanged stainless class150"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 150", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "758",
    slug: "serie-758-robinet-a-tournant-spherique-2-pieces-a-brides-acier-class300-adler",
    name: frEn("758 - Robinet à tournant sphérique 2 pièces à brides acier class300 ADLER", "758 — Ball valve two-piece flanged steel class300 ADLER"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 300", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "759",
    slug: "serie-759-robinet-a-tournant-spherique-2-pieces-a-brides-inox-class300-adler",
    name: frEn("759 - Robinet à tournant sphérique 2 pièces à brides inox class300 ADLER", "759 — Ball valve two-piece flanged stainless class300 ADLER"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 300", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "760",
    slug: "serie-760-robinet-a-tournant-spherique-2-pieces-a-brides-acier-class600-adler",
    name: frEn("760 - Robinet à tournant sphérique 2 pièces à brides acier class600 ADLER", "760 — Ball valve two-piece flanged steel class600 ADLER"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 600", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "761",
    slug: "serie-761-robinet-a-tournant-spherique-2-pieces-a-brides-inox-class600-adler",
    name: frEn("761 - Robinet à tournant sphérique 2 pièces à brides inox class600 ADLER", "761 — Ball valve two-piece flanged stainless class600 ADLER"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 600", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "762",
    slug: "serie-762-robinet-a-tournant-spherique-2-pieces-a-brides-acier-performance-pn16-40",
    name: frEn("762 - Robinet à tournant sphérique 2 pièces à brides acier Performance PN16/40", "762 — Ball valve two-piece flanged steel Performance PN16/40"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN16-40", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "763",
    slug: "serie-763-robinet-a-tournant-spherique-2-pieces-a-brides-inox-performance-pn16-40",
    name: frEn("763 - Robinet à tournant sphérique 2 pièces à brides inox Performance PN16/40", "763 — Ball valve two-piece flanged stainless Performance PN16/40"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN16-40", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "763l",
    slug: "serie-763l-robinet-a-tournant-spherique-2-pieces-split-body-f1-din-long-inox-pn10-40",
    name: frEn("763L - Robinet à tournant sphérique 2 pièces Split Body F1 DIN Long inox PN10/40", "763L — Ball valve two-piece Split Body F1 DIN Long stainless PN10/40"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "PN10-40", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "766",
    slug: "serie-766-robinet-a-tournant-spherique-2-pieces-a-brides-acier-class150-fe2",
    name: frEn("766 - Robinet à tournant sphérique 2 pièces à brides acier class150 FE2", "766 — Ball valve two-piece flanged steel class150 FE2"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 150", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "767",
    slug: "serie-767-robinet-a-tournant-spherique-2-pieces-a-brides-inox-class150-fe2",
    name: frEn("767 - Robinet à tournant sphérique 2 pièces à brides inox class150 FE2", "767 — Ball valve two-piece flanged stainless class150 FE2"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 150", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "768",
    slug: "serie-768-robinet-a-tournant-spherique-2-pieces-a-brides-acier-class300",
    name: frEn("768 - Robinet à tournant sphérique 2 pièces à brides acier class300", "768 — Ball valve two-piece flanged steel class300"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 300", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "769",
    slug: "serie-769-robinet-a-tournant-spherique-2-pieces-a-brides-inox-class300",
    name: frEn("769 - Robinet à tournant sphérique 2 pièces à brides inox class300", "769 — Ball valve two-piece flanged stainless class300"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 300", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "778",
    slug: "serie-778-robinet-a-tournant-spherique-2-pieces-acier-a-brides-class150",
    name: frEn("778 - Robinet à tournant sphérique 2 pièces acier à brides class150", "778 — Ball valve two-piece steel flanged class150"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 150", material: frEn("Acier", "Steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
  base({
    reference: "779",
    slug: "serie-779-robinet-a-tournant-spherique-2-pieces-inox-a-brides-class150",
    name: frEn("779 - Robinet à tournant sphérique 2 pièces inox à brides class150", "779 — Ball valve two-piece stainless flanged class150"),
    description: frEn(
      "Split body à brides, étanchéité JC — gamme catalogue.",
      "Split body flanged ball valve, JC sealing — catalog range.",
    ),
    dn: null, pn: "Class 150", material: frEn("Inox", "Stainless steel"),
    connectionType: "flanged-rf", standards: ["en10204"], sectorTags: ["energy","industry"],
    technicalSpecs: { connection: "flanged-rf", documentCount: 4 },
  }),
];
